// This file is auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > lib/types/database.ts
// Or use the Supabase dashboard to generate types

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            user_profiles: {
                Row: {
                    id: string
                    display_name: string | null
                    preferred_unit_system: 'metric' | 'imperial'
                    dietary_preferences: Json
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    display_name?: string | null
                    preferred_unit_system?: 'metric' | 'imperial'
                    dietary_preferences?: Json
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    display_name?: string | null
                    preferred_unit_system?: 'metric' | 'imperial'
                    dietary_preferences?: Json
                    created_at?: string
                    updated_at?: string
                }
            }
            recipes: {
                Row: {
                    id: string
                    name: string
                    description: string | null
                    cover_image_url: string
                    cooking_time_minutes: number
                    prep_time_minutes: number | null
                    servings: number
                    calories_per_serving: number | null
                    protein_grams: number | null
                    carbs_grams: number | null
                    fat_grams: number | null
                    difficulty_level: 'easy' | 'medium' | 'hard' | null
                    rating: number | null
                    rating_count: number
                    is_public: boolean
                    created_by: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    description?: string | null
                    cover_image_url: string
                    cooking_time_minutes: number
                    prep_time_minutes?: number | null
                    servings?: number
                    calories_per_serving?: number | null
                    protein_grams?: number | null
                    carbs_grams?: number | null
                    fat_grams?: number | null
                    difficulty_level?: 'easy' | 'medium' | 'hard' | null
                    rating?: number | null
                    rating_count?: number
                    is_public?: boolean
                    created_by?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    description?: string | null
                    cover_image_url?: string
                    cooking_time_minutes?: number
                    prep_time_minutes?: number | null
                    servings?: number
                    calories_per_serving?: number | null
                    protein_grams?: number | null
                    carbs_grams?: number | null
                    fat_grams?: number | null
                    difficulty_level?: 'easy' | 'medium' | 'hard' | null
                    rating?: number | null
                    rating_count?: number
                    is_public?: boolean
                    created_by?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            ingredients: {
                Row: {
                    id: string
                    name: string
                    category: string
                    default_unit: string
                    icon_emoji: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    category: string
                    default_unit: string
                    icon_emoji?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    category?: string
                    default_unit?: string
                    icon_emoji?: string | null
                    created_at?: string
                }
            }
            recipe_ingredients: {
                Row: {
                    id: string
                    recipe_id: string
                    ingredient_id: string
                    quantity: number
                    unit: string
                    preparation_note: string | null
                    is_optional: boolean
                    display_order: number
                }
                Insert: {
                    id?: string
                    recipe_id: string
                    ingredient_id: string
                    quantity: number
                    unit: string
                    preparation_note?: string | null
                    is_optional?: boolean
                    display_order: number
                }
                Update: {
                    id?: string
                    recipe_id?: string
                    ingredient_id?: string
                    quantity?: number
                    unit?: string
                    preparation_note?: string | null
                    is_optional?: boolean
                    display_order?: number
                }
            }
            recipe_steps: {
                Row: {
                    id: string
                    recipe_id: string
                    step_number: number
                    instruction: string
                    image_url: string | null
                    video_url: string | null
                    duration_minutes: number | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    recipe_id: string
                    step_number: number
                    instruction: string
                    image_url?: string | null
                    video_url?: string | null
                    duration_minutes?: number | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    recipe_id?: string
                    step_number?: number
                    instruction?: string
                    image_url?: string | null
                    video_url?: string | null
                    duration_minutes?: number | null
                    created_at?: string
                }
            }
            recipe_tags: {
                Row: {
                    id: string
                    name: string
                    slug: string
                    icon_emoji: string | null
                    display_order: number
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    slug: string
                    icon_emoji?: string | null
                    display_order?: number
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    slug?: string
                    icon_emoji?: string | null
                    display_order?: number
                    created_at?: string
                }
            }
            recipe_tag_mappings: {
                Row: {
                    recipe_id: string
                    tag_id: string
                    created_at: string
                }
                Insert: {
                    recipe_id: string
                    tag_id: string
                    created_at?: string
                }
                Update: {
                    recipe_id?: string
                    tag_id?: string
                    created_at?: string
                }
            }
            saved_recipes: {
                Row: {
                    user_id: string
                    recipe_id: string
                    notes: string | null
                    saved_at: string
                }
                Insert: {
                    user_id: string
                    recipe_id: string
                    notes?: string | null
                    saved_at?: string
                }
                Update: {
                    user_id?: string
                    recipe_id?: string
                    notes?: string | null
                    saved_at?: string
                }
            }
            meal_plan_entries: {
                Row: {
                    id: string
                    user_id: string
                    recipe_id: string | null
                    quick_note: string | null
                    meal_date: string
                    meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack'
                    servings: number
                    is_completed: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    recipe_id?: string | null
                    quick_note?: string | null
                    meal_date: string
                    meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack'
                    servings?: number
                    is_completed?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    recipe_id?: string | null
                    quick_note?: string | null
                    meal_date?: string
                    meal_type?: 'breakfast' | 'lunch' | 'dinner' | 'snack'
                    servings?: number
                    is_completed?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
            grocery_list_items: {
                Row: {
                    id: string
                    user_id: string
                    ingredient_id: string | null
                    custom_name: string | null
                    quantity: number
                    unit: string
                    category: string | null
                    is_checked: boolean
                    source_meal_plan_ids: string[]
                    notes: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    ingredient_id?: string | null
                    custom_name?: string | null
                    quantity: number
                    unit: string
                    category?: string | null
                    is_checked?: boolean
                    source_meal_plan_ids?: string[]
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    ingredient_id?: string | null
                    custom_name?: string | null
                    quantity?: number
                    unit?: string
                    category?: string | null
                    is_checked?: boolean
                    source_meal_plan_ids?: string[]
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            regenerate_grocery_list: {
                Args: {
                    p_user_id: string
                    p_start_date: string
                    p_end_date: string
                }
                Returns: void
            }
        }
        Enums: {
            meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack'
        }
    }
}
